[build]
builder = "nixpacks"
buildCommand = "echo 'Building services'"

[[services]]
name = "python"
root = "python"
buildCommand = "pip install -r requirements.txt"
startCommand = "python sort.py"

[[services]]
name = "java"
root = "java"
buildCommand = "mvn clean package"
startCommand = "java -jar target/sorting-api-1.0.0.jar"